version: '3.4'
services:
  database:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_USER: check_my_password
      POSTGRES_PASSWORD: check_my_password
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  webapp:
    build:
      context: .
      dockerfile: Dockerfile
    command: bin/rails server --port 3000 --binding '0.0.0.0'
    volumes:
      - .:/check_my_password
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/app/node_modules
    environment:
      RAILS_ENV: development
      DATABASE_HOST: database
      DATABASE_USERNAME: check_my_password
      DATABASE_PASSWORD: check_my_password
    ports:
      - "3000:3000"
    depends_on:
      - database

volumes:
  gem_cache:
  db_data:
  node_modules:
