name: check-my-password

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest

    env:
      RAILS_ENV: test
      DATABASE_USERNAME: user_test
      DATABASE_PASSWORD: password_test
      DATABASE_HOST: localhost

    services:
      postgres:
        image: postgres:9.6-alpine
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
        ports:
          - 5432:5432
        # Add a health check
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Ruby version specified in `.ruby-version`
        uses: eregon/use-ruby-action@master
      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: gem-cache-${{ hashFiles('Gemfile.lock') }}
      - name: Install dependencies
        run: |
          gem install bundler -v 2.2.5
          bundle config gems.contribsys.com ${{ secrets.BUNDLE_GEMS__CONTRIBSYS__COM }}
          bundle check --path vendor/bundle || bundle install --path vendor/bundle --jobs=4 --retry=3
      - name: Setup database
        run: |
          cp config/database.yml.sample config/database.yml
          rails db:setup
      - name: Run tests
        run: bundle exec rspec
  jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
